PATH=%PATH%;C:\me_ftp\labPEA\przegladZup\przegladZup\..\przegZup-CB\bin\Release
przegZup 5.txt LB
przegZup 6.txt LB
przegZup 8.txt LB
przegZup 9.txt LB
przegZup 10.txt LB
przegZup 11.txt LB
przegZup 12.txt LB
przegZup 13.txt LB
przegZup 15.txt LB
przegZup 17.txt LB
przegZup 18.txt LB
przegZup 5.txt all
przegZup 6.txt all
przegZup 8.txt all
przegZup 9.txt all
przegZup 10.txt all
przegZup 5.txt swap
przegZup 6.txt swap
przegZup 8.txt swap
przegZup 9.txt swap
przegZup 10.txt swap
przegZup 11.txt swap
przegZup 12.txt swap
przegZup 13.txt swap
przegZup 15.txt swap
przegZup 17.txt swap
przegZup 18.txt swap
przegZup 5.txt worse
przegZup 6.txt worse
przegZup 8.txt worse
przegZup 9.txt worse
przegZup 10.txt worse
przegZup 11.txt worse
przegZup 12.txt worse
przegZup 11.txt all
przegZup 13.txt worse
przegZup 12.txt all